---
title: "CLF"
author: "Nate Thomas"
date: "2023-03-28"
output: html_document
---

```{r setup, include=FALSE}
memory.limit(32000000)
memory.size(32000000)

YEAR = 2023

library(butcher)
library(R.utils)
library(utils)
library(dplyr)
library(plyr)
library(survey)
library(mltools)
library(data.table)
library(svMisc)
library(usethis)
library(lubridate)
library(plm)

source("gcs_interface.R")
cloud_prep()
```

```{r}
get_object("Profile 15 --- regression_dataset (2009-2022).csv", "demographics_project_raw") 
df1 <- read.csv("_downloaded_.csv")
unlink("_downloaded_.csv")
```

# Set reference groupgs:

```{r}
df1 <- df1 %>%
  mutate(year = as.factor(year),
         month = as.factor(month),
         state = as.factor(state),
         sex = as.factor(sex),
         race = as.factor(race),
         hisp = as.factor(hisp),
         married = as.factor(married),
         educ = as.factor(educ),
         disability = ifelse(disability == "No Disability", 0, 1),
         hearing = ifelse(hearing == "no hearing disabilty", 0, 1),
         seeing = ifelse(seeing == "no seeing disability", 0, 1),
         remembering = ifelse(remembering == "no remembering disability", 0, 1),
         mobility = ifelse(mobility == "no mobility disability", 0, 1),
         selfcare = ifelse(selfcare == "no selfcare disability", 0, 1),
         erranddifficulty = ifelse(erranddifficulty == "no errand difficulty disability", 0, 1))

df1 <- df1 %>% within(state <- relevel(state, ref = "NH"))
df1 <- df1 %>% within(sex <- relevel(sex, ref = "Men"))
df1 <- df1 %>% within(race <- relevel(race, ref = "White"))
df1 <- df1 %>% within(hisp <- relevel(hisp, ref = "Non-Hispanic nor Latino ethnicity"))
df1 <- df1 %>% within(married <- relevel(married, ref = "Married"))
df1 <- df1 %>% within(educ <- relevel(educ, ref = "High school graduates, no college"))

df1$id <- 1:nrow(df1)
```

# Possible selection combinations

```{r}
filterer <- data.frame(state = c("All","Any"),
           sex = c("All","Any"),
           race= c("All","Any"),
           hisp= c("All","Any"),
           married= c("All","Any"),
           educ= c("All","Any"),
           disability= c("All","Any"),
           hearing= c("All","Any"),
           seeing= c("All","Any"),
           remembering= c("All","Any"),
           mobility= c("All","Any"),
           selfcare= c("All","Any"),
           erranddifficulty= c("All","Any"),
           age1664 = c("All","Any"),
           age25up =  c("All","Any")) %>%
  tidyr::expand(state,sex,race,hisp,married,educ,disability,
                hearing,seeing,remembering,mobility,selfcare,
                erranddifficulty,age1664,age25up)

filterer <- filterer %>%
  filter(!(disability == "Any" & hearing == "Any") & 
         !(disability == "Any" & seeing == "Any") &
         !(disability == "Any" & remembering == "Any") &
         !(disability == "Any" & mobility == "Any") &
         !(disability == "Any" & selfcare == "Any") &
         !(disability == "Any" & erranddifficulty == "Any") &
         !(hearing == "Any" & seeing == "Any") &
         !(hearing == "Any" & remembering == "Any") &
         !(hearing == "Any" & mobility == "Any") &
         !(hearing == "Any" & selfcare == "Any") &
         !(hearing == "Any" & erranddifficulty == "Any") &
           
         !(seeing == "Any" & remembering == "Any") &
         !(seeing == "Any" & mobility == "Any") &
         !(seeing == "Any" & selfcare == "Any") &
         !(seeing == "Any" & erranddifficulty == "Any") &
           
         !(remembering == "Any" & mobility == "Any") &
         !(remembering == "Any" & selfcare == "Any") &
         !(remembering == "Any" & erranddifficulty == "Any") &
           
         !(mobility == "Any" & selfcare == "Any") &
         !(mobility == "Any" & erranddifficulty == "Any") &
           
         !(selfcare == "Any" & erranddifficulty == "Any") &
           
         !(age1664 == "Any" & age25up == "Any"))
```


```{r}
mod_logit <- list()
```


```{r}
y=2019
i = 1536
for (y  in 2022:2019){
 for (i in dim(filterer)[1]:1){
  print(i)
  mod_df <- df %>%
    mutate(y = ifelse(laborforce=="In the laborforce",1,0)) %>%
    filter(civilian == "civilian", age16up == 1, year == yr) %>%
    select(y, id, contains("pwsswgt"), year, month, state, sex, race, hisp, married, educ, disability, hearing, seeing, remembering, mobility, selfcare, erranddifficulty, age1664, age25up)
  
  inter <- ""
  if (filterer[i,"state"] == "Any" & filterer[i,"disability"] == "Any") {
    inter <- "state*disability"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"hearing"] == "Any") {
    inter <- "state*hearing"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"seeing"] == "Any") {
    inter <- "state*seeing"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"remembering"] == "Any") {
    inter <- "state*remembering"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"mobility"] == "Any") {
    inter <- "state*mobility"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"selfcare"] == "Any") {
    inter <- "state*selfcare"
  }
  if (filterer[i,"state"] == "Any" & filterer[i,"erranddifficulty"] == "Any") {
    inter <- "state*erranddifficulty"
  }
  if (filterer[i,"state"] == "All") {
    mod_df <- mod_df %>% select(-state)
  }
  if (filterer[i,"sex"] == "All") {
    mod_df <- mod_df %>% select(-sex)
  }
  if (filterer[i,"race"] == "All") {
    mod_df <- mod_df %>% select(-race)
  }
  if (filterer[i,"hisp"] == "All") {
    mod_df <- mod_df %>% select(-hisp)
  }
  if (filterer[i,"married"] == "All") {
    mod_df <- mod_df %>% select(-married)
  }
  if (filterer[i,"educ"] == "All") {
    mod_df <- mod_df %>% select(-educ)
  }
  if (filterer[i,"disability"] == "All") {
    mod_df <- mod_df %>% select(-disability)
  }
  if (filterer[i,"hearing"] == "All") {
    mod_df <- mod_df %>% select(-hearing)
  }
  if (filterer[i,"seeing"] == "All") {
    mod_df <- mod_df %>% select(-seeing)
  }
  if (filterer[i,"mobility"] == "All") {
    mod_df <- mod_df %>% select(-mobility)
  }
  if (filterer[i,"selfcare"] == "All") {
    mod_df <- mod_df %>% select(-selfcare)
  }
  if (filterer[i,"erranddifficulty"] == "All") {
    mod_df <- mod_df %>% select(-erranddifficulty)
  }
  if (filterer[i,"remembering"] == "All") {
    mod_df <- mod_df %>% select(-remembering)
  }
  if (filterer[i,"age1664"] == "All") {
    mod_df <- mod_df %>% select(-age1664)
  }
  if (filterer[i,"age25up"] == "All") {
    mod_df <- mod_df %>% select(-age25up)
  }
  mod_design <- svydesign(id=~id, weights=~pwsswgt, data=mod_df)
  variables <- names(filterer[which(filterer[i,] == "Any")])
  if (all(filterer[i,] == "All")){
    mod_logit[[i]]  <- svyglm(y~year+month,
                        family = quasibinomial,
                        design = mod_design)
    mod_summary <- mod_logit[[i]]%>% summary()
    mod_summary$deviance.resid <- NA
  }
  if (!all(filterer[i,] == "All")){
    mod_logit[[i]]  <- svyglm(paste("y~",paste("year+month+",variables,collapse = "+"),inter,"+1"),
                        family = quasibinomial,
                        design = mod_design)
    mod_summary <- mod_logit[[i]]%>% summary()
    mod_summary$deviance.resid <- NA
  }
  
  mod_logit[[i]]$residuals <- NA
  mod_logit[[i]]$fitted.values <- NA
  mod_logit[[i]]$effects <- NA
  mod_logit[[i]]$qr <- NA
  mod_logit[[i]]$linear.predictors <- NA
  mod_logit[[i]]$weights <- NA
  mod_logit[[i]]$prior.weights <- NA
  mod_logit[[i]]$y <- NA
  mod_logit[[i]]$model <- NA
  mod_logit[[i]]$data <- NA
  mod_logit[[i]]$survey.design <- NA

  mod_logit[[i]]$family$linkfun <- NA
  mod_logit[[i]]$family$dev.resid <- NA
  mod_logit[[i]]$family$variance <- NA
  mod_logit[[i]]$family$dev.resids <- NA
  mod_logit[[i]]$family$aic <- NA
  mod_logit[[i]]$family$validmu <- NA
  mod_logit[[i]]$family$valideta <- NA

  mod_logit[[i]]$R <- NA
  mod_logit[[i]]$family$initialize <- NA
  mod_logit[[i]]$deviance <- NA
  mod_logit[[i]]$null.deviance <- NA
  mod_logit[[i]]$iter <- NA
  mod_logit[[i]]$df.residual <- NA
  mod_logit[[i]]$df.null <- NA
  mod_logit[[i]]$call <- NA
  
  attr(mod_logit[[i]]$terms, ".Environment") <- NULL

  saveRDS(mod_logit[[i]], paste("gen",YEAR,"_analysis",yr,"_",i,"lf_models.rds",sep=""))
  saveRDS(mod_summary, paste("gen",YEAR,"_analysis",yr,"_",i,"lf_models_summary.rds",sep=""))
}

mod_logit[[i]] <- NA 
}
```
