---
title: "CLF"
author: "Nate Thomas"
date: "2023-03-28"
output: html_document
---

```{r setup, include=FALSE}
memory.limit()
memory.size()

library(butcher)
library(R.utils)
library(utils)
library(dplyr)
library(plyr)
library(survey)
library(mltools)
library(data.table)
library(svMisc)
year = 2023
library(usethis)

source("gcs_interface.R")
cloud_prep()

```

```{r}
rm(df1)
if(!exists("df1")){
  cloud_prep()
  get_object("Profile 15 --- regression_dataset (2009-2022).csv", "demographics_project_raw") 
  df1 <- read.csv("_downloaded_.csv")
  unlink("_downloaded_.csv")
}
if(exists("df1")){
  load(".RData")
}
```

# Set reference groupgs:

```{r}
df1 <- df1 %>%
  mutate(year = as.factor(year),
         month = as.factor(month),
         state = as.factor(state),
         sex = as.factor(sex),
         race = as.factor(race),
         hisp = as.factor(hisp),
         married = as.factor(married),
         educ = as.factor(educ),
         disability = ifelse(disability == "No Disability", 0, 1),
         hearing = ifelse(hearing == "no hearing disabilty", 0, 1),
         seeing = ifelse(seeing == "no seeing disability", 0, 1),
         remembering = ifelse(remembering == "no remembering disability", 0, 1),
         mobility = ifelse(mobility == "no mobility disability", 0, 1),
         selfcare = ifelse(selfcare == "no selfcare disability", 0, 1),
         erranddifficulty = ifelse(erranddifficulty == "no errand difficulty disability", 0, 1))

df1 <- df1 %>% within(state <- relevel(state, ref = "NH"))
df1 <- df1 %>% within(sex <- relevel(sex, ref = "Men"))
df1 <- df1 %>% within(race <- relevel(race, ref = "White"))
df1 <- df1 %>% within(hisp <- relevel(hisp, ref = "Non-Hispanic nor Latino ethnicity"))
df1 <- df1 %>% within(married <- relevel(married, ref = "Married"))
df1 <- df1 %>% within(educ <- relevel(educ, ref = "High school graduates, no college"))

df1$id <- 1:nrow(df1)
```

# Possible selection combinations

```{r}
mod_filterer <- data.frame(state = c("All","Any"),
           sex = c("All","Any"),
           race= c("All","Any"),
           hisp= c("All","Any"),
           married= c("All","Any"),
           educ= c("All","Any"),
           disability= c("All","Any"),
           hearing= c("All","Any"),
           seeing= c("All","Any"),
           remembering= c("All","Any"),
           mobility= c("All","Any"),
           selfcare= c("All","Any"),
           erranddifficulty= c("All","Any"),
           age1664 = c("All","Any"),
           age25up =  c("All","Any")) %>%
  tidyr::expand(state,sex,race,hisp,married,educ,disability,
                hearing,seeing,remembering,mobility,selfcare,
                erranddifficulty,age1664,age25up)

mod_filterer <- mod_filterer %>%
  filter((disability == "Any" |
          hearing == "Any" |
          seeing == "Any" |
          remembering == "Any" |
          mobility == "Any" |
          selfcare == "Any"|
          erranddifficulty == "Any") &
         
         married == "All" &
         hisp == "All" &
         educ == "All" &
         age1664 == "All" &
         age25up == "All" &
           
         (state == "Any" & (disability == "Any" |
                            hearing == "Any" |
                            seeing == "Any" |
                            remembering == "Any" |
                            mobility == "Any" |
                            selfcare == "Any"|
                            erranddifficulty == "Any")) &
          
         !(disability == "Any" & hearing == "Any") & 
         !(disability == "Any" & seeing == "Any") &
         !(disability == "Any" & remembering == "Any") &
         !(disability == "Any" & mobility == "Any") &
         !(disability == "Any" & selfcare == "Any") &
         !(disability == "Any" & erranddifficulty == "Any") &
         !(hearing == "Any" & seeing == "Any") &
         !(hearing == "Any" & remembering == "Any") &
         !(hearing == "Any" & mobility == "Any") &
         !(hearing == "Any" & selfcare == "Any") &
         !(hearing == "Any" & erranddifficulty == "Any") &
           
         !(seeing == "Any" & remembering == "Any") &
         !(seeing == "Any" & mobility == "Any") &
         !(seeing == "Any" & selfcare == "Any") &
         !(seeing == "Any" & erranddifficulty == "Any") &
           
         !(remembering == "Any" & mobility == "Any") &
         !(remembering == "Any" & selfcare == "Any") &
         !(remembering == "Any" & erranddifficulty == "Any") &
           
         !(mobility == "Any" & selfcare == "Any") &
         !(mobility == "Any" & erranddifficulty == "Any") &
           
         !(selfcare == "Any" & erranddifficulty == "Any") &
           
         !(age1664 == "Any" & age25up == "Any")) %>%
  select(-educ,-hisp,-married, -age1664, -age25up) 
mod_filterer  
save.image(".RData")
```


```{r}
state_onehot <- mod_df1 %>% select(state) %>% data.table() %>% one_hot()

for (i in dim(mod_filterer)[1]:1){
  print(i)
  mod_df1 <- df1 %>%
    mutate(y = ifelse(laborforce=="In the laborforce",1,0)) %>%
    filter(civilian == "civilian", age16up == 1) %>%
    select(y, id, contains("pwsswgt"), year, month, state, 
           sex, race, disability, hearing, seeing, remembering,
           mobility, selfcare, erranddifficulty)

  if (mod_filterer[i,"state"] == "All") {
    mod_df1 <- mod_df1 %>% select(-state)
  }
  if (mod_filterer[i,"sex"] == "All") {
    mod_df1 <- mod_df1 %>% select(-sex)
  }
  if (mod_filterer[i,"race"] == "All") {
    mod_df1 <- mod_df1 %>% select(-race)
  }
  if (mod_filterer[i,"disability"] == "All") {
    mod_df1 <- mod_df1 %>% select(-disability)
  }else{
    disstate_onehot <- state_onehot*mod_df1$disability
  }
  if (mod_filterer[i,"hearing"] == "All") {
    mod_df1 <- mod_df1 %>% select(-hearing)
  }else{
    disstate_onehot <- state_onehot*mod_df1$hearing  
  }
  if (mod_filterer[i,"seeing"] == "All") {
    mod_df1 <- mod_df1 %>% select(-seeing)    
  }else{
    disstate_onehot <- state_onehot*mod_df1$seeing  
  }
  if (mod_filterer[i,"mobility"] == "All") {
    mod_df1 <- mod_df1 %>% select(-mobility)
  }else{
    disstate_onehot <- state_onehot*mod_df1$mobility 
  }
  if (mod_filterer[i,"selfcare"] == "All") {
    mod_df1 <- mod_df1 %>% select(-selfcare)
  }else{
    disstate_onehot <- state_onehot*mod_df1$selfcare
  }
  if (mod_filterer[i,"erranddifficulty"] == "All") {
    mod_df1 <- mod_df1 %>% select(-erranddifficulty)
  }else{
    disstate_onehot <- state_onehot*mod_df1$erranddifficulty
  }
  if (mod_filterer[i,"remembering"] == "All") {
    mod_df1 <- mod_df1 %>% select(-remembering)
  }else{
    disstate_onehot <- state_onehot*mod_df1$remembering 
  }
  colnames(disstate_onehot) <- paste(colnames(disstate_onehot),"dis",sep="_")
  mod_df1 <- mod_df1 %>% cbind(disstate_onehot)

  mod_design <- svydesign(id=~id, weights=~pwsswgt, data=mod_df1)

  variables <- names(mod_df1)
  mod_logit[[i]]  <- svyglm(paste("y~year+month+",paste(variables,collapse = "+"),"-1"),
                      family = quasibinomial,
                      design = mod_design,
                      x=F,
                      y=F)
  mod_temp_summary <- mod_logit[[i]] %>% summary()
  mod_temp_summary$deviance.resid <- NA

# mod_logit[[i]]$residuals <- NA
# mod_logit[[i]]$fitted.values <- NA
# mod_logit[[i]]$effects <- NA
# mod_logit[[i]]$qr <- NA
# mod_logit[[i]]$linear.predictors <- NA
# mod_logit[[i]]$weights <- NA
# mod_logit[[i]]$prior.weights <- NA
# mod_logit[[i]]$y <- NA
# mod_logit[[i]]$model <- NA
# mod_logit[[i]]$data <- NA
# mod_logit[[i]]$survey.design <- NA
# mod_logit[[i]]$family$linkfun <- NA
# mod_logit[[i]]$family$dev.resid <- NA
# mod_logit[[i]]$family$variance <- NA
# mod_logit[[i]]$family$dev.resids <- NA
# mod_logit[[i]]$family$aic <- NA
# mod_logit[[i]]$family$validmu <- NA
# mod_logit[[i]]$family$valideta <- NA
# mod_logit[[i]]$R <- NA
# mod_logit[[i]]$family$initialize <- NA
# mod_logit[[i]]$deviance <- NA
# mod_logit[[i]]$null.deviance <- NA
# mod_logit[[i]]$iter <- NA
# mod_logit[[i]]$df.residual <- NA
# mod_logit[[i]]$df.null <- NA
# mod_logit[[i]]$call <- NA
# attr(mod_logit[[i]]$terms, ".Environment") <- NULL
# 
# saveRDS(mod_logit[[i]], paste(year,"_",i,"lf_models.rds",sep=""))
# saveRDS(mod_temp_summary, paste(year,"_",i,"lf_models_summary.rds",sep=""))

cloud_prep()
#send_object(paste(year,"_lf_model.rds",sep=""),
#            "demographics_project_storage",
#            name=paste(year,"_",i,"lf_models.rds",sep=""))
#send_object(paste(year,"_",i,"lf_models_summary.rds",sep=""),
#              "demographics_project_storage",
#              name=paste(year,"_",i,"lf_models_summary.rds",sep=""))

#  unlink(paste(year,"_",i,"lf_models.rds",sep=""))
#  unlink(paste(year,"_",i,"lf_models_summary.rds",sep=""))
#  mod_logit[[i]] <- NA
}
```



